In [2]:
import numpy as np


In [4]:
x=[[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]]

In [8]:
x

[[[1, 2, 3], [1, 2, 3], [1, 2, 3]],
 [[1, 2, 3], [1, 2, 3], [1, 2, 3]],
 [[1, 2, 3], [1, 2, 3], [1, 2, 3]]]

In [7]:
y=np.array(x)
y

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [11]:
z=[1,2,3,4,5]
z

[1, 2, 3, 4, 5]

In [22]:
np.zeros(3)

array([0., 0., 0.])

In [24]:
np.zeros((3,2)) #describe the size of matrix in between()

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [31]:
np.zeros((3,2)) -5

array([[-5., -5.],
       [-5., -5.],
       [-5., -5.]])

In [20]:
np.ones(3)

array([1., 1., 1.])

In [27]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
np.ones((3,4)) +1  #if write +1 it will print +2 if write -2 it will print -1

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [40]:
np.eye(4) 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
np.eye(4) -2

array([[-1., -2., -2., -2.],
       [-2., -1., -2., -2.],
       [-2., -2., -1., -2.],
       [-2., -2., -2., -1.]])

In [44]:
np.arange(10)  # 1 id array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.arange(50).reshape(5,10)  #2d metrix row=5,col=10

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [48]:
np.linspace(0,10)  # it will devide a point into eqaul parts

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [50]:
np.linspace(0,10,5) #start end total value u want

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [108]:
p=[1,2,3,4,5]
p

[1, 2, 3, 4, 5]

In [61]:
np.max(p) #if value in list then use np to find max,min

5

In [64]:
q=np.array(p)
q

array([1, 2, 3, 4, 5])

In [113]:
q.argmax() #it will give the index of max value

4

In [115]:
q.argmin()

0

In [67]:
q.max() #if value in array use .max() function to find max

5

In [69]:
q.min()

1

In [70]:
q.std()

1.4142135623730951

In [75]:
r=np.random.rand(5)
r

array([0.73719063, 0.26092953, 0.98613583, 0.61260266, 0.27820657])

In [77]:
r1=np.random.randn(5) #randn for negative value
r1

array([ 0.00493588,  0.40103596, -1.48194262,  0.81538101,  0.92355272])

In [79]:
np.random.randint(1,100) #if u need random integer no

80

In [116]:
np.random.randint(5)

4

In [128]:
lis=np.arange(0,21)
lis


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [129]:
lis[9]

9

In [123]:
lis[-1]


20

In [130]:
len(lis)

21

In [131]:
lis[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
lis[2:5]

array([2, 3, 4])

In [134]:
lis[2:10:2]

array([2, 4, 6, 8])

In [136]:
lis[-10:-1]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [137]:
lis2=lis[5:15]=40 #any change in lis2 also affect lis

In [139]:
lis2

40

In [141]:
lis

array([ 0,  1,  2,  3,  4, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 15, 16,
       17, 18, 19, 20])

In [142]:
xx=[1,2,3,4,5,6]
xx

[1, 2, 3, 4, 5, 6]

In [146]:
y=xx.copy() #now change in y dose't effect y
y 


[1, 2, 3, 4, 5, 6]

In [152]:
y=np.array(y)
y


array([1, 2, 3, 4, 5, 6])

In [155]:
y[1:5]=80
y

array([ 1, 80, 80, 80, 80,  6])

In [157]:
xx

[1, 2, 3, 4, 5, 6]

In [161]:

pp=np.arange(25).reshape(5,5)
pp

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [164]:
pp[2][3] #indexing in 2D

13

In [166]:
pp[4][2]

22

In [168]:
pp[4,2]


22

In [170]:
#slicing in 2D  [row start:row end,col start:col end]
pp[0:2,2:]


array([[2, 3, 4],
       [7, 8, 9]])

In [172]:
o=np.arange(1,20) #conditional selection
o

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [174]:
o[o>12]

array([13, 14, 15, 16, 17, 18, 19])

In [175]:
o[o<12]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [177]:
o[o%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [179]:
#mathmatical operation
# add-element have ro be same in botn array
m=np.arange(10)
m

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [181]:
n=np.arange(10,20)
n

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [184]:
l=m+n
l

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [186]:
np.log(n)

array([2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [188]:
np.sin(n)


array([-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721])

In [190]:
n.max()


19

In [191]:
np.max(n)

19